### PR TITLE
Update DynamoText assembly version for 2.0

### PR DESCRIPTION
**Pull request by alfarok**
This PR updates the DynamoText assembly version to 2.0 to align with Core 2.0.  This change is required to coincide with the `.pkg` file included with the package on the package manager.

### Reviewer
@kirschm

### CODE REVIEW

**Comment by mjkkirschner** [comment]
LGTM

**Comment by QilongTang** [comment]
LGTM

**Comment by alfarok** [comment]
@mjkkirschner @QilongTang I updated the assembly for MTK and DynamoText.  I will merge both now and update DynamoText on the PM for testing and ping you guys when it's done so you can verify it's downloading correctly before I do MTK.

**Comment by QilongTang** [comment]
@alfarok Nice sequence, let's do it

**Pull request merged**
